# Base Image
FROM node:16-alpine as builder

# Install dependencies and run the builder
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Additional image
FROM nginx

# Copy anything from previous stage
COPY --from=builder /app/build /usr/share/nginx/html
